### ISSUE TITLE
[TO-DO] Sparkle 2.1.0

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Sparkle#16]
![imaged](https://github.com/MrScautHD/Sparkle/assets/65916181/b00df8df-e0eb-4986-a2a5-d42dba71d1d2)

Sparkle Engine
=========
A fast, Cross-platform .NET 7 C# 11 game engine.

## Features
- [x] `Directed, Pointed Light` Component
- [ ] `Loading Screen (LoadingGUI)` by starting the game and switching scenes.
- [x] `Register System`
- [x] `IContentType` for giving some informations by loading content
- [x] `Frustum`

## GUI Elements
- [ ] `CheckBox`
- [ ] `DropDownBox`
- [ ] `TextBox`
- [ ] `ValueBox`
- [ ] `Spinner`
- [ ] `Slider`
- [ ] `SliderBar`
- [ ] `ProgressBar`

![style_table](https://github.com/MrScautHD/Sparkle/assets/65916181/7b885d75-3e1f-4d6d-a397-e8cee16b9335)

## Not possible (Right now)
- [ ] `Angle` Impliment Vulkan, Direct3D and Metal https://github.com/ChrisDill/Raylib-cs/pull/186
- [ ] `Check F12` https://github.com/ChrisDill/Raylib-cs/pull/186

**Comment by Gammer0909** [comment]
By the way, I think the OpenGL flag issue should be removed, as the owner of Raylib-cs has closed it, and therefore not be implementing it.

**Comment by MrScautHD** [comment]
> By the way, I think the OpenGL flag issue should be removed, as the owner of Raylib-cs has closed it, and therefore not be implementing it. 

He closed it because he thought this is for flags for the window settings bit it is still coming for the msbuild system so for the .csproj file

**Comment by Gammer0909** [comment]
> He closed it because he thought this is for flags for the window settings but it is still coming for the msbuild system so for the .csproj file

Oh, he moved it to another issue. I see, thanks.
