### ISSUE TITLE
 [TO-DO] Sparkle 2.2.0

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Sparkle#17]
![imaged](https://github.com/MrScautHD/Sparkle/assets/65916181/b00df8df-e0eb-4986-a2a5-d42dba71d1d2)

Sparkle Engine
=========
A fast, Cross-platform .NET 8 C# 12 game engine.

## Features
- [x] `Raylib-cs-v6.0.0`
- [x] `OpenTK` Lib
- [x] Add `ContainsOrientedBox` Method for ``Frustum``
- [x] `ModelAnimations` impliment them in the ModelRenderer (Component) to handle animations of the model.
- [x] `Effect System`
- [x] `Material Builder`
- [x] `PBREffect` [(PBR)](https://github.com/raysan5/raylib/blob/master/examples/shaders/resources/shaders/glsl330/pbr.fs)

![image](https://github.com/MrScautHD/Sparkle/assets/65916181/8e6df65c-825b-4239-8e16-a39e68e1bb1c)

## Fix
- [x] Fix JoltPhysics do not work on MacOS.
- [x] Get rid of Java namespaces https://github.com/MrScautHD/Sparkle/pull/21.
- [x] Remove `GameSettings.ContentPath` and `ContentManager(string directory)`.
- [x] Disallow the utilization of a `ContentProcessor` without the required  `ContentType`: 
```cs
Content.Load<Font>(new FontContent("path"));

// Fix Should be:
Content.Load(new FontContent("path"));
```

**Comment by leftbones** [comment]
More examples would be helpful, it's not at all very clear where to begin with this engine!

**Comment by MrScautHD** [comment]
> More examples would be helpful, it's not at all very clear where to begin with this engine!

Sure, but you could use the wiki: https://github.com/MrScautHD/Sparkle/wiki
