### ISSUE TITLE
[TO-DO] Sparkle 3.0.0

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Sparkle#22]
![imaged](https://github.com/MrScautHD/Sparkle/assets/65916181/b00df8df-e0eb-4986-a2a5-d42dba71d1d2)

Sparkle Engine
=========
A fast, Cross-platform .NET 8 C# 12 game engine.

## Features
- [x] Replace `JoltPhysics` with `Jitter Physics 2` (https://github.com/notgiven688/jitterphysics2)
- [x] Add `Skybox`
- [x] Add `FileHelper`
- [x] Add `RandomHelper`
- [x] Add `MaterialProcessor` and `MaterialContent`.
- [x] Add `ContentManager.AddUnmanagedContent`.
- [x] `Website` (https://sparkle-engine.com/)
- [x] Add `CryptoProvider`
- [x] Replace `Config` and `ConfigBuilder` with `JsonConfig` and `JsonConfigBuilder`
- [x] Replace `FileManager` with `FileAccessor`

## Fix
- [x] Save content (Files like shaders, logo...) in the nuget packet.
- [x] Fix materials of models get not unloaded.
- [x] Support the right Attribute data format. https://github.com/raysan5/raylib/issues/3807
- [x] Fix rendering models can significantly reduce their power consumption requirements.
