### ISSUE TITLE
[TO-DO] Sparkle 4.0.0

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Sparkle#24]
<p align="center" style="margin-bottom: 0px !important;">
  <img width="512" src="https://github.com/MrScautHD/Sparkle/assets/65916181/9f378f17-5468-4dd4-bc72-ffd396a90639" alt="Logo" align="center">
</p>

<h1 align="center" style="margin-top: 0px;">Greetings to Sparkle-v4.0.0! 🎉</h1>
<h4 align="center">Delve into the to-do list outlining the enhancements and updates slated for the 4.0.0 release!</h4>

## Move to [Raylib-CSharp](https://github.com/MrScautHD/Raylib-CSharp)
- [x] Done

## Features
- [x] Add `GlobalPos` and `OffsetPos` to `Component`.
- [x] Disable Screen recording by pressing F12.
- [x] Add `Box2D` for `2D Physics`.
- [x] Replace `MaterialBuilder` with `MaterialManipulator`.
- [x] Make Effect more efficent, if they disabled do not call the Update method... and update Shader variables just by setting the value instead of every tick.

## Filter Effects
- [x] Add `FXAA` Shader. (https://github.com/raysan5/raylib/issues/4038)
- [x] Add `GrayScale` Shader.
- [x] Add `Posterization` Shader.
- [x] Add `DreamVision` Shader.
- [x] Add `Pixelizer` Shader.
- [x] Add `CrossHatching` Shader.
- [x] Add `CrossStitching` Shader.
- [x] Add `Predator` Shader.
- [x] Add `Scanlines` Shader.
- [x] Add `Fisheye` Shader.
- [x] Add `Sobel` Shader.
- [x] Add `Bloom` Shader.
- [x] Add `Blur` Shader.

## Check
- [x] Check if Nuget publish works by doing a Github release.

## Fix
- [x] Resolve issue where Animations pause instead of stoping.
- [x] Resolve issue where Skybox let you not set colors.
- [x] Resolve issue where you can not set the Active Camera.
- [x] Resolve issue where the Skybox render after the entities.
- [x] Resolve the issue of documentation not being uploaded on NuGet.
- [x] Resolve the issue of duplicated GUI element textures by adjusting their dimensions larger than the texture itself.
- [x] Resolve the issue where the `Stop`, `Pause` method in `AnimationPlayer` was broken.
