### ISSUE TITLE
 [TO-DO] Sparkle 4.1.0

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Sparkle#25]
<p align="center" style="margin-bottom: 0px !important;">
  <img width="512" src="https://github.com/MrScautHD/Sparkle/assets/65916181/9f378f17-5468-4dd4-bc72-ffd396a90639" alt="Logo" align="center">
</p>

<h1 align="center" style="margin-top: 0px;">Greetings to Sparkle-v4.1.0! 🎉</h1>
<h4 align="center">Delve into the to-do list outlining the enhancements and updates slated for the 4.1.0 release!</h4>

## Major Change!
- [ ] Replace [`Raylib-CSharp`](https://github.com/MrScautHD/Raylib-CSharp) with [`Bliss`](https://github.com/MrScautHD/Bliss).

## Features
- [ ] Add `Scene Save System` (By adding entities with `MapObject = true` the data get stored in a .json file).
- [ ] Add `SoftBody`.
- [ ] Add `3D Audio`
- [ ] Add `GPU based Animation Player` (With Interpolation)
- [ ] Add `Shadows, Fog, Sun...` to PBR Shader.
- [ ] Add `Particles` (GPU based).
- [ ] Add some `2D Shaders`.
- [ ] Add `Terrain Generation`.
- [ ] Add `VideoPlayer`. (Looking for a usefull lib)
- [ ] Add `Loading Screen (LoadingGUI)` by starting the game and switching scenes.
- [x] Improve Effect (Remove the If checks it do not really effect the performance)
- [x] Remove `GifManager` got useless.
- [x] Add a `warn message` by disposing a already disposed object.
- [x] Reworked `Entity` and `Component` Disposing.
- [x] Add `GetComponents` method to Entity. 
- [x] Replace in `RegistryManager` the `AddType` method with the `Add` method.

## Fix
- [x] Resolve issue where the `CryptoProvider.Encrypt` method was broken.
- [x] Resolve issue where `JsonConfig` did not `Encrypted`.
- [x] Resolve issue where the `ModelAnimationPlayer` not reset the animation pose by playing it again.

## GUI Elements
- [ ] Check the mouse if showing when opening and by closing set the mouse type before.
- [ ] `CheckBox`
- [ ] `DropDownBox`
- [ ] `TextBox`
- [ ] `ValueBox`
- [ ] `Spinner`
- [ ] `Slider`
- [ ] `SliderBar`
- [ ] `ProgressBar`

![style_table](https://github.com/MrScautHD/Sparkle/assets/65916181/7b885d75-3e1f-4d6d-a397-e8cee16b9335)

**Comment by MrScautHD** [comment]
This `to-do` is get replaced with https://github.com/MrScautHD/Sparkle/issues/26
