### ISSUE TITLE
🧊 [TO-DO] Sparkle 2.0.0.0

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Sparkle#6]
![imaged](https://github.com/MrScautHD/Sparkle/assets/65916181/b00df8df-e0eb-4986-a2a5-d42dba71d1d2)

Sparkle Engine
=========
A fast, Cross-platform .NET 7 C# 11 game engine.

## Features
- [x] `Physics`
- [x] `Touch`
- [x] `Collision (Shape)`

## GUI Elements
- [x] `Label`
- [x] `Button`
- [x] `Toggle`

![style_table](https://github.com/MrScautHD/Sparkle/assets/65916181/7b885d75-3e1f-4d6d-a397-e8cee16b9335)

## Bugs
- [x] `MSAA` 
- [x] `Icon`
- [x] `System Info`
- [x] `Logo get not unloaded`
- [x] `Close Method crash the game`
- [x] `Few missing Raylib methods / functions`

## Core
- [x] Clean up
